version: '3.8'
services:
  # ================= FRONTEND =================
  frontend:
    build: ./frontend
    ports:
      - "6000:80"  # Host:Container
    volumes:
      - ./frontend/src:/app/src  # Hot-reload development
      - /app/node_modules  # Hindari override node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix file watching in Docker
    depends_on:
      - backend
    networks:
      - my-network

  # ================= BACKEND =================
  backend:
    build: ./backend
    ports:
      - "3000:3000"  # Host:Container
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:pass@db:5432/mydb  # Contoh koneksi DB
    networks:
      - my-network

  # ================= DATABASE (Opsional) =================
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    ports:
      - "5432:5432"

# ================= VOLUMES & NETWORKS =================
volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge